                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">Horario de Aulas y Laboratorios 2024-3</h1>
                            <p class="py-3 text-center">
                                Actualización 30/08/2024 20:12 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio M Laboratorios</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1odxVWPoC5d0fLfAUzilitOCM_f64euFx/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LM102
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1QnFbOU9AzNjbf-S8danY4xb9j2y_Yjzh/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LM106
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jeKkcS8tlmPRTV5KNfpv2pRUl1p3AnCg/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LM107
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio M Aulas</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1Knvoh5ak4DupZdH-i_WxFM6Eo8RWoKVt/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M101
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1dXLVpdXmLlPyx22nKCThy7frgblonWXB/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M103
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/16EFwE8k76xO5Z9aXV7bCk3OTafnWbT3T/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M104
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1G5ysw5OwnpvMCpsBTYSeUxMPm_YiJ068/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M105
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/15mkAG-4s9kDJKZXNsLV6eJK61TJNFH5Q/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M108
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>