                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">Horario de Aulas y Laboratorios 2023-2</h1>
                            <p class="py-3 text-center">
                                Actualización 29/04/2023 11:01 a.m.
                            </p>
                            <div class="row">
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio D</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1pfXRbhbw7FMtPdXU-HljT_QcJco6aDeL/view?usp=share_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            D100
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/19Y2jnVmhLDvtVV519iwJvd4pSfiwU_Os/view?usp=share_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            D201
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1D8fynON8jkhzgAJKP1upHn7yPRcDpYbH/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            D202
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/17RVKUicNbNO6ii9dsRQEItgMfdVRAmxl/view?usp=share_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            D206
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1_zmNAU_0GSmOiLFq5XuwApKURbfgAay4/view?usp=share_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            D207
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio K</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1FGTO8mjyaiArG8mAY2OmdjUtgRSl--dV/view?usp=share_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            K105
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1_8oeZOMXR5GgrrZvMFLgXYyX32LVViWv/view?usp=share_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            K108
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1LlJSE9xvSE-tZVS4_Tnf8JtXQ4Wis_Qf/view?usp=share_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            K109
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1nzkygGS8ci3I7DfB9ZGLuDP7eGPFyjTZ/view?usp=share_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            K Dirección Matutino
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1GIc7w6Y8AUecDNN_yOSzRonIwXkVEo2r/view?usp=share_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Auditorio K P-B
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio J Biblioteca</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1FAwA0Pfg8yQGIzTfPtP9gCsi-3PjiWsH/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Lab Biblioteca
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 mx-auto">

                                </div>
                            </div>
                        </div>
                    </div>