                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">Horario de Aulas y Laboratorios 2025-1</h1>
                            <p class="py-3 text-center">
                                Actualización 19/12/2024 11:36 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio M Aulas</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1vMbypGBoEp58cYt6oOm-_mb0uQnAtmn1/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M101
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/13tGFWaKSASkC79XSELTpRL683hWL_LeD/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M103
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/11AeWCriUgrjQ-KvP2RTNIOYmp5nl43Ij/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M104
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1p-9aryINoz7qwOfx2yhJeOt59pdtOFUZ/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M105
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1Kegc5A2i7Zvxs9hMvYGJv4k8bH2pp1z4/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M201
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1g4CVYlT7TZ2XPvH5MkTR7aqdmExYlyZE/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M205
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1VbH6zuaXFP2O0mz7na017g2MxvVMHtOj/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M206
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1HiOTY3yw24kEpgUiCGTkPuaxQhZ6o7ex/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M207
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1tYuL403N4h9M1OYjD5dx3wgFzioiGqC2/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M209
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1wIVzKevcAtUUw2ChQlfCtvfsmgMMwF79/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M210
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1wKAjqPO8PsYNDOOubMSHvs1sMoFAr6ln/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M211
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio M Laboratorios</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1KLoXp2Dlng-S7CYkMbkjsodkHYKHrl2j/view?usp=drive_link" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M102 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1YLy4bppI94jIUdyeGrAMjgZEUPooDFF8/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M106 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1mSSFf-mTJzyav0Z2plYibeG3C0CmFWb-/view?usp=drive_link" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M107 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1YQQDScM1QfhZz4caQT0NRI5RUQ73Y1Jl/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M108 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1yhqzKV49Ts-fMaqfiCyBxN9DeLpMKkAH/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M202 (LABORATORIO MAC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1hYorrlVTX6B3PbN82XKvkF9rqohGAfa3/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M203 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1Z3HRH-_N40thw0bnjg5BKzByUA5n5NQM/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M204 (LABORATORIO MAC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/19b_d7c_ozZOfexieAN_rOX3eiwMXvRne/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LAB. INFORMATICA BASICA (PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M208 (LABORATORIO MAC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1-2ZCTJVDpGaiTIpbnHgkqc5ocxxJuNas/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                BITMAP (LABORATORIO MAC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/19qavVKfOlP-KhPcN3MTJGwc0siYX34qT/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LABORATORIO DISEÑO (PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <br>
                            <br>
                            <div class="row">
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio L Aulas</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1hbtoCBmWHWxDpCRlmbjKXeBv8BxUXyt8/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                L102
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1__KP6ZQJiKLGDjj0ZN3W4UAQW5EaL0rt/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                L105
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1xmiKlSiNSqbewdMQeBrciKnN48k9I_1p/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                L106PA
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Centro CCAI (H)</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1eBzTR9mzqDsqdQ2ZwUSWuCfE4LLY1-XR/view?usp=drive_link">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                CCAI MAC
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1Yoa1N3cUAwxMQIVp3P2BbsbvZ6yS713-/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                CCAI PC
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>