                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">Horario de Aulas y Laboratorios 2025-2</h1>
                            <p class="py-3 text-center">
                                Actualización 27/04/2025 08:02 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio M Aulas</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1IZkRkdz4qI7EUVeNwx_JIZTFHJMYV-kv/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M101
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1y3RgO1Sm_5B9phBBAkCvCTnT6-VaA0Om/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M103
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1ZaCA7aE3e499Hh2ZiPXkb9cucyMAWGOO/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M104
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/14hS0AzdJlqNAm8TUE5Zhx5L2YDqaY6s1/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M201
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1nHJzSRGBbBJr6ZeZVg9R5XpuWdBBUJts/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M205
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1F_fu0dRPjGQXEpcgu9CN4QkBrX4ro8rd/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M206
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1f9FAtiAZIZDbaJhV9v8C3Csb-pMIqJ-R/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M207
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1OOGbpPTz34Rbm1NI6ch8-ZQsmlIFTaul/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M208
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/17-a2e7X8E-g1ZrzhUkuKVbEU3uBvrTEU/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M209
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1C9CFtBFcSOktLsMgD5lGm7e1ghQAdkmv/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M210
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1WqGIGrRnp7L1ZBKc3F7a5HE9OnFlddx0/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M211
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio M Laboratorios</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1XZOnkJrbrqR2ZRvNGQu1rVH-ZA4JMI0U/view?usp=drive_link" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M102 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/147wUHDFksbJEoJMDFfmnFXprmwnPtpA3/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M106 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1gm-lIN-QgEf3u5OJ_vyp9wxIDQ5BGgAG/view?usp=drive_link" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M107 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1WERwDz8jDK-uDK657clCwiEVVX1b7j2d/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M108 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1nO-QhuXtV2gRonsT8Rs7h6D4PuikyX0b/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M202 (LABORATORIO MAC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1f0ul3h28TFW6sYqjlPY6CiOP4wounOqs/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M203 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1HipKHn27tb78Wc12f5Jil--gZggLfvV4/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M204 (LABORATORIO MAC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jS0DW7s4xYMMrmeTO3WQsUD9bVSGMYO7/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LAB. INFORMATICA BASICA (PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1OOGbpPTz34Rbm1NI6ch8-ZQsmlIFTaul/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M208 (LABORATORIO MAC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/179_O2iPcPznJF4faZzn-efu6LJjR2KMq/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                BITMAP (LABORATORIO MAC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1-68AwPrJnvbkD97yBV3a8F84PktJX0Qu/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LABORATORIO DISEÑO (PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <br>
                            <br>
                            <div class="row">
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio L Aulas</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1hnhlnSbWcxEvCGLcdcDmNI_J4lzfh0LA/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                L102
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1qk92-NYdgOIgovvWPENvWX7ClP2NK1It/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                L105
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1_y1tW-M2VZAjbuajjl0ea2UwdFj93A_g/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                L106
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Centro CCAI (H)</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1j5UP9m5F5EFwssInwZjlD3SgT70ZA1Hz/view?usp=drive_link">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                CCAI MAC
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1KkRHZzA2rcTtin-xCx08j9D9rCgmkT_Q/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                CCAI PC
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>