                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">Horario de Aulas y Laboratorios 2025-1</h1>
                            <p class="py-3 text-center">
                                Actualización 19/12/2024 11:36 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio M Aulas</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M101
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M103
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jeKkcS8tlmPRTV5KNfpv2pRUl1p3AnCg/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M104
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jeKkcS8tlmPRTV5KNfpv2pRUl1p3AnCg/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M105
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jeKkcS8tlmPRTV5KNfpv2pRUl1p3AnCg/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M201
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jeKkcS8tlmPRTV5KNfpv2pRUl1p3AnCg/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M205
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jeKkcS8tlmPRTV5KNfpv2pRUl1p3AnCg/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M206
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jeKkcS8tlmPRTV5KNfpv2pRUl1p3AnCg/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M207
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jeKkcS8tlmPRTV5KNfpv2pRUl1p3AnCg/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M209
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jeKkcS8tlmPRTV5KNfpv2pRUl1p3AnCg/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M210
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jeKkcS8tlmPRTV5KNfpv2pRUl1p3AnCg/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M211
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio M Laboratorios</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M102 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M106 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M107 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M108 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M202 (LABORATORIO MAC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M203 (LABORATORIO PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M204 (LABORATORIO MAC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LAB. INFORMATICA BASICA (PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                M208 (LABORATORIO MAC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                BITMAP (LABORATORIO MAC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LABORATORIO DISEÑO (PC)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                CCAI PC
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                CCAI MAC
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>