                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">Concentrado de calificaciones 2022-2</h1>
                            <p class="py-3 text-center">
                                Actualización 24/08/2022 10:01 a.m.
                            </p>
                            <div class="row">
                                <div class="col-md-6 col-12">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>IRD</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/11_FNXGN7LOgBL5k_yszeLTf8q7TwGzjh/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Concentrado IRD 101
                                                        </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1kqyRLETrvnmtHMlgX83SXIPR9rSYJU-N/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Concentrado IRD 301
                                                        </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1_Ps14KKamSc8GyVcCStBBRsA-KrJCIPn/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Concentrado IRD 302
                                                        </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1Pu5frjfbiv-PuUNdhVcsbe_hbllIRSrw/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Concentrado IRD 303
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1OtrjWzdtXjCHKAHXvKqrMRHCeum08uuf/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Concentrado IRD 401
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/174rnqTIs9rDDQn1-Fqqgy8Z4DW8skJbC/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Concentrado IRD 501
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 col-12">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>IRIC</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1awIusNgVKB6uWfgtSRKWz8ccaXQOCUPZ/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Concentrado IRIC 901
                                                        </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/14Oyjj3aV5vRThrxndl6hQmlx9zaZB3uu/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Concentrado IRIC 902
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>