                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h3 class="py-3 text-center text-danger">Actualización de los Programas Educativos por Competencias Profesionales de la Coordinación General de Universidades Tecnológicas y Politécnicas.</h1>
                            <!-- <p class="py-3 text-center">
                                Actualización 30/05/2022 09:13 p.m.
                            </p> -->
                            <div class="row">
                                <div class="col-12">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Documentos</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1hmO0O8x2Suj4uEN8zvKrgknveVGDQBET/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            DOC-20201123-WA0048.pdf
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>                                                
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1PGtFx9RHppOfXA3EtqVK0m0GvrY0ZaCm/view?usp=share_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Dictamen_de_Acreditación_de_Carreras.pdf
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>