                        <div class="row contenido">

                            <div class="col-12 rounded shadow-sm rounded pb-5">
                                
                                <h1 class="py-3 text-center">Horarios de Grupo 2023-3</h1>
                                <p class="py-3 text-center">
                                    Actualización 28/08/2023 12:30 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>IRD</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/10jUgKnCn55lzy3Po4YalbNMjLUkgXtxj/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 101
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1I4E8EJQsZc1SxTd-tQJt7pc-y1tAfdBk/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 102
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1cpa3ilc_UOeGIPupYcYxYlwztZ7ktanC/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 103 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1LAROEOaNlPWjcTV5ggtaZ0YThbh78FaS/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 104 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/11lxhhRUArGw7LoaEjwHUpfFX86NEoxoq/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 301
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/10YkbvwQdTMm6xWHl1IPzMevCgA7e1QYQ/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 401
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>                                                
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1lE_AFCup6kVMDMVpqyhXu7Uw77ZtARt4/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 402
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>                                                
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1ZiwbmeWgYfJvhKhvnCQRi9xa3-Oy3mOx/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 403 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>                                                
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1WF8tD29KtmlEFor43ba5LYmvRj4dXbdb/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 501
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>                                                
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>IRICE</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1oaPjjm9a-yXqDMXUiAEXHY9xOWxKjI1H/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRICE 701
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1h9epX0FotpFi-t0IVKt8-zXOy1r0qt_J/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRICE 702
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1CyE41KvjbsCPW0k-ZxI5T3GikzWpqcEB/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRICE 901
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/171hMhwMSUtPogPlJW8rdQ2Yq5NjnRsyl/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRICE 1001
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>