                        <div class="row contenido">

                            <div class="col-12 rounded shadow-sm rounded pb-5">
                                
                                <h1 class="py-3 text-center">Horarios de Grupo 2025-2</h1>
                                <h2 class="py-3 text-center">Ciencia de Datos</h2>
                                <p class="py-3 text-center">
                                    Actualización 27/04/2025 08:01 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>CD</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1LJatkFFjXa2VVYE7QouL-ZQ0nZgqYukm/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    CD301
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                <br>
                                <br>
                                <h2 class="py-3 text-center">Infraestructura de Redes Digitales e Ingeniería en Redes Inteligentes y Ciberseguridad</h2>
                                <p class="py-3 text-center">
                                    Actualización 27/04/2025 08:01 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>IRD</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1h39F4Ml1Wqd-i6sBoMHYyTKNAcEmEGvG/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRD301
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1e5BFRBHVDQlgh7wHZSvr6eQOs7_Sn0iU/view?usp=drive_linkk" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRD302
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>IRICE</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1SC4nOZ8EEEkpHjvR9PHEN6HR2VRRgHLh/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE801 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/14arzoIwE74_mdgu5Gjq2ESmqvzARrm8N/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE901 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1gqpq734NpMF3Mjcc9LhwZhwzvrORSp-G/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE902 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <br>
                                <br>
                                <h2 class="py-3 text-center">Diseño y Animación Digital</h2>
                                <p class="py-3 text-center">
                                    Actualización 19/12/2024 10:12 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>DAD</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1A8Y5fW7v7BJ_n1rs4scLmaCGtnPdU4MH/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD201
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1L8jvH2X_Wq5yIX9fvsPJ-Z0yxM1vomzr/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD301
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1DQCKzMOVWYi_W2itOkaqfZsdUGIag0e1/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD302
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1KbzWCRKhKldRiXLzpdmxaGhYQDC_a27R/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD303
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1hu2ulAg5lU9OO2fkxmVtZIjgDvNZXmKc/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD304
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1rVRTJxCHmjW6M17oC7R4qIWClnm_XsvC/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD305 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1ktdVQJdiByfaRPKokzVcT3GzI-7JsjsU/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD306 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1Y3mVZ6tZf5Ol1nxTVNIU5Bfi3QKCYJwD/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD307 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1wlKJuQjOY3nfDoEqx1Wvlox3KgqB1MFD/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD308 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1N1Mz9VRp9SeXWZtWyicyVbLRAi2bhC1m/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD309 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <br>
                                <br>
                                <h2 class="py-3 text-center">Diseño Digital área Animación y Licenciatura en Diseño Digital y Producción Audiovisual</h2>
                                <p class="py-3 text-center">
                                    Actualización 27/04/2025 08:01 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>DDA</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1L6aIJlZj1eOr-eRN7B1ALbJpMAdSe1ko/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA401
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/17JRsgPPk5Z89ITLG5a6y9KbRWZucKRjD/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA501
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>LDDPA</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1CF-0oFW31xCOujJvinszbWoXipXBh-LP/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA701
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1lW8-47FxyvIRhtexB7CLZIO2ouL9MAlV/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA801
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1YB3x1Czouk6_yq0ii24Fflj5WyuQbR_y/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA802
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1AXWjS7MvU-oVppCugh6wCi6yeIXNxPZx/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA901
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1xejz9IwprVPXrx3npa3cIZppW5wRpWox/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA902
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/19qNYwlhHwthhHCMqwVyP_TXHbGyyTd1W/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA903
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1yACng0VKwZptxxAMrq1_4W8sIIPgXngz/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPAE904 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1hj4q52zfxQTJhflReBufknFVtZj0CmtV/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA1001
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <br>
                                <br>
                                <h2 class="py-3 text-center">Descarga todos los Horarios de Grupo</h2>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Diseño, Redes y Ciencia de Datos</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1nuvvDgogUqBtfEGImqyczBjx0q6jDfvP/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    Horarios de Grupo 2025-2
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>