                        <div class="row contenido">

                            <div class="col-12 rounded shadow-sm rounded pb-5">
                                
                                <h1 class="py-3 text-center">Horarios de Grupo 2024-1</h1>
                                <p class="py-3 text-center">
                                    Actualización 23/12/2023 20:21 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>IRD</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1kEQs-IzkO1UL8_VVrQzkNoTk2dpAFqgb/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 201
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1EUNGXU7ggUJZpTbdofPUkf8cum5Xqk4u/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 202
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1HoDvX9R3zjmRRUBj7Kji-VRm7TmaEB2I/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 203 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1R7DncigwhQ78a38MKy8loXBg1j-agbu7/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 204 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1L-5O6pIJHN2EFzkJ296pw2VDZ61Ntqbq/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 401
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1V7gTOUpQ7Ke9TrGATrVxVYOkP_7PcigV/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 501
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>                                                
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/14gdehw9LJPnyVk83N9TlBOTRw_T4Nmwi/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 502
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>                                                
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1ijSd82DWbedeOApMh5b-nnKwxDa43Svi/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD 503
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>   

                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>IRICE</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1fAoFmdnK4yazjOwOlot0iC-SGrXHIZIC/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRICE 801
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1KugEmI2kCIIi49nKHyK3iLJFdtfAARZ7/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRICE 802
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1ZRjPXEiWT-ND4SP7Rm7HJYHPptVUrI3g/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRICE 1001
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>