                        <div class="row contenido">

                            <div class="col-12 rounded shadow-sm rounded pb-5">
                                
                                <h1 class="py-3 text-center">Horarios de Grupo 2025-1</h1>
                                <h2 class="py-3 text-center">Ciencia de Datos</h2>
                                <p class="py-3 text-center">
                                    Actualización 19/12/2024 10:12 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>CD</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1zGtwTTyQOD6rgxuLlTQEkvtYDy-mKdiK/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    CD201
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                <br>
                                <br>
                                <h2 class="py-3 text-center">Infraestructura de Redes Digitales e Ingeniería en Redes Inteligentes y Ciberseguridad</h2>
                                <p class="py-3 text-center">
                                    Actualización 19/12/2024 10:12 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>IRD</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1b7CBq9yyTjx0kcS7LJCRvJcmHLgbQwLt/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRD201
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1wDJzzATfY_hSgFz4lr9eSTdH-L4WXceR/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRD202
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1E2TEKhCWaTX0dNq1tC7FLqHSdl8Yf2-2/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRD501
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1GqEs5g1IlS_a8uczr6bUOYgjMMOUrAqb/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRD502
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>IRICE</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1OvhYS5LmQlIcP5tTuJ6cEkYc65pwZxuY/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE701 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1DBZYlIEqLVjUrPk-Bp5rZQrGR3F4DZAc/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE801 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1ygzaljrHLFHTdB4yRnyZj7o0iddosDVg/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE802 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <br>
                                <br>
                                <h2 class="py-3 text-center">Diseño y Animación Digital</h2>
                                <p class="py-3 text-center">
                                    Actualización 19/12/2024 10:12 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>DAD</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1oqnZI4Cw6MTo2Zvh7P9vDtUZktyy3eNM/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD101
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1mMYxEqQuSMXkaa9x3aINbokUij1Gmpwb/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD201
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1Os-SFmKs7b92s9FT-YuOb7Yphxo9hjAp/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD202
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/174YJ8v84dvzJ4WGnF4LQ5xck5A7nVEux/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD203
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/18lVsQWqIVMTksih7OhtyMLNPvSSTvmQk/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD204
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1wXZLVcTw2V3Stp-QNiUG-GyTLSd5tspd/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD205 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1wrwAUR_a02UPuPoPCV2nVNa6CzU6N1k5/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD206 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1Gg6uLWSCyXbb2NOdcVJF-YT-Bglfyfll/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD207 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1RSBRGS4iF_kLN078VC5DlIu-5C-uAgQh/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD208 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1PzM8PIHg0qCAlg0_Cks3xedLjkpoJDkG/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD209 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <br>
                                <br>
                                <h2 class="py-3 text-center">Diseño Digital área Animación y Licenciatura en Diseño Digital y Producción Audiovisual</h2>
                                <p class="py-3 text-center">
                                    Actualización 19/12/2024 10:12 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>DDA</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1T05kUg8b_Q6Lm-1eSr9KSL08xXYex_vy/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA301
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1yizgjehXZyxjjQu0VglW6Pz6s3bWtAcq/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA401
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1v2ZAH-xctxPCv26cs7p6i-qN9hZUcSea/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA501
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/17PHR9JcRfX1YJ5aLKuMhFTfaCd2R0-Ic/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA502
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1Bx2wqkQsf3prm-_yKLkhMByUw21kMOBc/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA503
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1nbBWrkTJDknIkwIVBwHno_frjRnWxQ0X/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA504 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1iCWlWBVg0W3EPcFh_h0wWi3drjutF9pK/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA505 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>LDDPA</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1etiqiapJ-r62XQGoUidg8kFjiuBx4pqV/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA701
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1Ee_8ET23R0OGDuc1VMr_-x5F_c3KRafM/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA702
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1Yfk91hKcleIzUKAfkqFLqlTFWf1bdNsR/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA801
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1pnZlcKjOSjYje1w634NcDc2ccOyGOrgA/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA802
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1BEqbilhjvnwbCdf_6kEFaoZmJzCYth0v/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA803
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1KoTt5_OaBt2lRMvBIuoy_IaNWl0BWxjr/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPAE804 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1niAAOUD-ptxNFWnLC6jUpwfJJDBo43w8/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA901
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1_r_-QmfmLR4CjOviMXYNV5F3ybChzb9F/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA1001
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <br>
                                <br>
                                <h2 class="py-3 text-center">Descarga todos los Horarios de Grupo</h2>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Diseño, Redes y Ciencia de Datos</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1RQ7Mv7WO8_AINghp1hMRTpSbnYfuM7PE/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    Horarios de Grupo 2025-1
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>