                        <div class="row contenido">

                            <div class="col-12 rounded shadow-sm rounded pb-5">
                                
                                <h1 class="py-3 text-center">Horarios de Grupo 2024-3</h1>
                                <p class="py-3 text-center">
                                    Actualización 30/08/2024 20:12 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>IRD</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1z3tBsU_SamjkzijSRA0DuFmYAIAeot-7/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRD101
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1axf_vKDsPsBw9DlcpXPDhBiUbIQ5yhXp/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRD102
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1i4IOUq_rX8OmubACOjh48yrZRpLFyZnb/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRD401
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1yI6TGQXg3NwAMRMAZSPkMQhIi7jRGauU/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRD402
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>IRICE</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1-tcI3Jc4sKyVku8YjPT_dBhWH-KVVyO-/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE701 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1j6H_ZPnbdFoUkHUE_2roINLsf6dr0C50/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE702 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1OTIEQ9n6QQKlG9VKXAUxR08oXgyTjKbY/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE1001 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1_zNu2fgxhWIV1p8K-L3BwoikLuDQv00P/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE1002 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>