                    <div class="row contenido">
                        <div class="col-12 mx-auto text-center mb-5">
                            <div>
                                <video class="video-fluid z-depth-1 mx-auto text-center" autoplay loop controls muted width="100%">
                                    <source src="videos/serDragon.mp4" type="video/mp4"/>
                                </video>                              
                            </div>
                        </div>

                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5">
                            <br><br><br>
                            <h1 class="py-3 text-center text-danger mt-5">Concurso <b>Cibertalento Edoméx 2022<b></h1>
                            <a href="https://comecyt.edomex.gob.mx/node/334" target="_blank" rel="noopener noreferrer">                            
                                <img src="img/Cibertalento.png" class="img-fluid my-5" alt="Cibertalento 2022">
                            </a>
                            <h3>
                                CONVOCATORIA PROMOCIÓN 2022: ABIERTA
                            </h3>
                            <h4>
                                Acerca de
                            </h4>
                            <p class="py-3">
                                La acción “Cibertalento Edoméx 2022”, tiene como finalidad principal apoyar e incentivar el desarrollo profesional de personas interesadas en temas de ciberseguridad. 
                                <br>
                                Los aspirantes deberán generar ideas innovadoras mediante la presentación de propuestas tales como aplicativos (Apps), páginas de internet, videos educativos, modelos de prevención, cursos de prevención u otros elementos que contribuyan a fortalecer la ciberseguridad en las áreas de:
                                <br>
                                <ol>
                                    <li>Educación digital.</li> 
                                    <li>Ciberacoso.</li> 
                                    <li>Pliicía cibernética.</li> 
                                    <li>Ciberseguridad para PYMES.</li> 
                                    <li>Ciudadanía cibersegura.</li> 
                                </ol>
                            </p>
                            <h4>¿A quién está dirigido?</h4>
                            <p class="py-3">Desarrollo de aplicativos.
                                Jóvenes mexiquenses menores de 29 años que actualmente estén cursando sus estudios en instituciones educativas públicas o privadas establecidas en el Estado de México, o que hayan egresado de alguna carrera enfocada a las áreas de atención. 
                            </p>
                            <h4><b>Áreas de atención.</b></h4>
                            <p class="py-3">
                                Los interesados en participar mediante la presentación de sus propuestas deberán contar con conocimientos en, al menos, alguna de las siguientes áreas:
                            
                            <ul>
                                <li>Desarrollo de aplicativos.</li>
                                <li>Tecnologías de la información.</li>
                                <li>Sistemas computacionales.</li>
                                <li>Lenguajes de programación.</li>
                                <li>Ciberseguridad.</li>
                                <li>Mecatrónica.</li>
                                <li>Internet de las cosas.</li>
                                <li>Ingeniería social.</li>
                                <li>Tecnologías educativas.</li>
                                <li>Otras áreas similares.</li>
                            </ul>
                            </p>
                            <h4><b>Documentos.</b></h4>
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>
                                            <div class="liLinks my-1">
                                                <a href="https://comecyt.edomex.gob.mx/sites/comecyt.edomex.gob.mx/files/files/cibertalento/CIBERTALENTO%20CONV-22-ACT%205-9-22_FINAL.pdf" target="_blank" rel="noopener noreferrer">
                                                    <div class="centrado-v">
                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                    Convocatoria(CIBERTALENTO CONV-22-ACT 5-9-22_FINAL.pdf)
                                                    </div>
                                                </a>
                                            </div>
                                        </td>
                                    <tr>
                                        <td>
                                            <div class="liLinks my-1">
                                                <a href="https://comecyt.edomex.gob.mx/sites/comecyt.edomex.gob.mx/files/files/cibertalento/9%20Aviso%20de%20Privacidad%20Integral%20Cibertalento_V3%20TRANSPARENCIA_0.pdf" target="_blank" rel="noopener noreferrer">
                                                    <div class="centrado-v">
                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                    Aviso de Privacidad Integral.pdf
                                                    </div>
                                                </a>
                                            </div>
                                        </td>
                                    <tr>
                                        <td>
                                            <div class="liLinks my-1">
                                                <a href="https://comecyt.edomex.gob.mx/sites/comecyt.edomex.gob.mx/files/files/cibertalento/9%20Aviso%20de%20Privacidad%20Simplificado%20Cibertalento_V3%20TRANSPARENCIA_0.pdf" target="_blank" rel="noopener noreferrer">
                                                    <div class="centrado-v">
                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                    Aviso de Privacidad Simplificado.pdf
                                                    </div>
                                                </a>
                                            </div>
                                        </td>
                                    <tr>
                                        <td>
                                            <div class="liLinks my-1">
                                                <a href="https://comecyt.edomex.gob.mx/sites/comecyt.edomex.gob.mx/files/files/cibertalento/T%C3%A9rminos%20y%20condiciones%20politicas%20de%20seguridad_V4%20TRANSPARENCIA.pdf" target="_blank" rel="noopener noreferrer">
                                                    <div class="centrado-v">
                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                    Términos y condiciones.pdf
                                                    </div>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <br>
                            <h4>Realiza tu registro en el siguiente enlace:</h4>
                            <p class="py-3">
                                <ul>
                                    <li>
                                        <a href="https://cibertalento.com" target="_blank" rel="noopener noreferrer">https://cibertalento.com</a>
                                    </li>
                                </ul>
                            </p>


                            
                        </div>
                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5"></div>

                        <!-- <div class="col-12 rounded shadow-sm rounded pb-5 mt-5">
                            <h1 class="py-3 text-center text-danger mt-5">Beneficiados por Beca Ciencia 2022</h1>
                            <img src="img/becaCiencia.png" class="img-fluid my-3" alt="Beneficiados por Beca Ciencia 2022">
                            <p class="py-3">
                                
                                <a class="liLinks" style="color: blue;" href="https://drive.google.com/file/d/16OUCR9ktWH_nEbVfZLg05cYWzf9QGKn_/view?usp=sharing" target="_blank" rel="noopener noreferrer">Link de Beneficiados.</a>
                                <br>
                                <br>
                            </p>
                            
                        </div>

                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5">
                            <h1 class="py-3 text-center text-danger">Tarjeta Joven</h1>
                            <img src="img/tarjetaJoven.png" class="img-fluid my-3" alt="Beneficiados por Beca Ciencia 2022">
                            <p class="py-3">
                                
                                <a class="liLinks" style="color: blue;" href="https://drive.google.com/file/d/16OUCR9ktWH_nEbVfZLg05cYWzf9QGKn_/view?usp=sharing" target="_blank" rel="noopener noreferrer">Link de Beneficiados.</a>
                                <br>
                                <br>
                                Nota: Todos los beneficiados por el programa <b>“Tarjeta Joven”</b> deberán presentarse en <b>"Becas"</b> ubicado en el edificio <b>“J”</b> y <b>cumplir con los documentos referidos en la convocatoria</b>, a más tardar el día <b>Jueves 26 de mayo de 2022</b>.
                                <br>
                                <br>
                                <a style="color: blue;" href="https://drive.google.com/file/d/16OUCR9ktWH_nEbVfZLg05cYWzf9QGKn_/view?usp=sharing" target="_blank" rel="noopener noreferrer">Link de Beneficiados.</a>

                            </p>
                            
                        </div> -->
                    </div>