                    <div class="row contenido">
                        <br>
                        <br>
                        <div class="ol-12 mx-auto text-center pb-5 mb-5" style="text-align: center;">
                            <h1>DIVISIÓN ACADÉMICA DE</h1>
                            <h1>Telemática</h1>
                            <br>
                            <p style="text-align: center;">
                                Atención: <a href="mailto:dirac.telematica@utfv.edu.mx"><b>dirac.telematica@utfv.edu.mx</b></a>
                                <br>
                                Tel: <a href="tel:+525526493143"><b>55-2649-3143 Ext: 234</b>
                                <!-- </a> Whats: <a href="https://api.whatsapp.com/send?phone=5573912775"><b>55-7391-2775</b></a> -->
                                
                            </p>
                            <br>
                            <br>
                        </div>
                        <div class="col-12 mx-auto text-center pb-5 mb-5">
                            <div>
                                <video class="video-fluid z-depth-1 mx-auto text-center" autoplay loop controls muted width="100%">
                                    <source src="videos/serDragon.mp4" type="video/mp4"/>
                                </video>                              
                            </div>
                            <br>
                            <br>
                        </div>

                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5"></div>
                        <br>
                            <h1>Becas para el Bienestar por Aprovechamiento Académico</h1>
                            <p>para el ciclo 2024-2025. Este programa busca apoyar a estudiantes regulares con un promedio mínimo de 8.5 y cuyos ingresos familiares estén por debajo de la línea de bajos recursos. Se otorgará un apoyo económico mensual de $800.00, sujeto a disponibilidad presupuestal. Los interesados deben registrarse electrónicamente entre el 14 y el 18 de octubre de 2024, cumpliendo con requisitos específicos, como presentar documentos que acrediten su situación académica y económica. Los resultados se publicarán del 27 al 29 de noviembre de 2024, y los beneficiarios deberán imprimir el dictamen de asignación. Es importante que los solicitantes mantengan actualizada su información de contacto y cumplan con todos los requisitos para evitar la cancelación de la beca.</p>
                            <br>
                            <a href="https://drive.google.com/file/d/18oklssgQL4GyG_Z7l3CATK3XhDJUFlze/view?usp=sharing">
                                <img src="img/BannerBeca.jpg" class="img-fluid" alt="Calendario Escolar">
                            </a>
                            <br>
                            <br>
                        </div>
                        <br>
                        <br>
                        

                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5">
                            <h2>Calendario Escolar 2024-2025</h2>
                            <br>
                            <a href="https://drive.google.com/file/d/1iCKKXq87VLQNj3DrCfn81XK3Yq9Z5J0i/view?usp=sharing">
                                <img src="img/calendario2024.jpg" class="img-fluid" alt="Calendario Escolar">
                            </a>
                            <br>
                            <br>
                        </div>

                      

                    </div>