                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">Listas de Grupo 2022-3</h1>
                            <p class="py-3 text-center">
                                Actualización 29/08/2022 17:12 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-6 col-12">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>IRD</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1S9tmozdOyp7Vw0IeLztgIqKD3RcH-i34/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRD 101
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1we1sEHXaKxvE93sW4XrMgM6OMvNXxZhR/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRD 102
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRD 103 (Pendiente)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1n4G-cr28lbGSIj1jSvcNCsamJ5zTLoul/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRD 201
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRD 401
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRD 402
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jxR4ln_0B4izFz0wJ5cHwJy2cRgFxo0Q/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRD 501
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 col-12">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>IRIC</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRICE 701 (Pendiente)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/10Gg85J5TYikplg_IONM6t2fch5b3Fem3/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRIC 1001
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1UqPuWMxAlxbfYzszoEiHAnn33ayj0zaz/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRIC 1002
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>