<div class="row contenido">

    <div class="col-12 rounded shadow-sm rounded pb-5">
        
        <h1 class="py-3 text-center">Listas de Grupo 2025-1</h1>
        <h2 class="py-3 text-center">Ciencia de Datos</h2>
        <p class="py-3 text-center">
            Actualización 19/12/2024 10:12 p.m.
        </p>
        <div class="row">
            <div class="col-md-6 col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>CD</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1cWl8BWqA0t2R8S9TZqFlrG9Q-UH2PmjR/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            CD201
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <br>
        <br>
        <h2 class="py-3 text-center">Infraestructura de Redes Digitales e Ingeniería en Redes Inteligentes y Ciberseguridad</h2>
        <p class="py-3 text-center">
            Actualización 19/12/2024 10:12 p.m.
        </p>
        <div class="row">
            <div class="col-md-6 col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>IRD</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1W8z2ug2Q9u-aqv8VR0a4uBbr9muCCtK6/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRD201
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/137VECeRS_CMWdJfzRYPKyrzS65SvY3eL/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRD202
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1TA6JUP5HrBjETJSOTPPkr7iKV5VChmt-/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRD501
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1PBWJWi8uAcgkCBnyR0wDN-WM7Yv8sUQs/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRD502
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="col-md-6 col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>IRICE</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRICE701 (EJECUTIVA)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRICE801 (EJECUTIVA)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRICE802 (EJECUTIVA)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br>
        <br>
        <h2 class="py-3 text-center">Diseño y Animación Digital</h2>
        <p class="py-3 text-center">
            Actualización 19/12/2024 10:12 p.m.
        </p>
        <div class="row">
            <div class="col-md-6 col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>DAD</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1jGsc6j_dzr1EFuEmmAl79i0EPeQBMrho/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD101
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1kiXz5roCdw7XwlvBnpCcTLor0cnpSzmh/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD201
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1EScxXtO2aE0fogeb-wNKtLbkXtRaxyfm/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD202
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1DzgHaKESEccj2i3_XLmhf9y5J6N0_-YN/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD203
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1LQ_jE6XXD9gvzezm6OYTfBWzUEh5IJxc/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD204
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1E4IEU-f4nW9UUZHVo75upLP2t9g80LBV/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD205 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/15YAdiTFqiAZkGOpK5vKR4glLh3PYJtsS/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD206 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1vIl0FvDv4roXXGqRSQAqV11bbiJqrazR/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD207 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1cnhWZbkbD17n4dHIZnjto3HhWk45wBlO/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD208 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/19bmfZ-OcRk1UU3qqmEIemulRMspc8-oh/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD209 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br>
        <br>
        <h2 class="py-3 text-center">Diseño Digital área Animación y Licenciatura en Diseño Digital y Producción Audiovisual</h2>
        <p class="py-3 text-center">
            Actualización 19/12/2024 10:12 p.m.
        </p>
        <div class="row">
            <div class="col-md-6 col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>DDA</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1LCPkdmNy1vy6JRNunAVefTAIzJal8Mwb/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA301
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1ZTrljZwzmrUXUbugcf_Z7K3ZAd-QvU-L/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA401
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1156ZOx3pf2r9vQ8v3iDmNRBeMpVSlgOx/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA501
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1djbyrjah6KGw2Ii0o9dRrZ93gGwVvWUB/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA502
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1azJkTW8vSq1hF36TAx30058Cd5W_MLfi/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA503
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1NWgDKxqKwFagWGlazFV7lEZNAlVjutmp/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA504 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1tWRQaGFNWpyL6fQusdJYhiSdhLBHiIsc/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA505 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1sNLqlZ2ve7_6SBCoqCySF2QOHMaigmrP/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA601 (Estadía)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="col-md-6 col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>LDDPA</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1aommlEWvYRhM5F2op92MmQNVNCczw2GI/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA701 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/167u5b-D1RWKU_4LMn1876xmLuUudhNOU/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA801 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1_qdR766fg0ZSr_T0TDDJXFMVmMk_ONN9/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA802 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1ubqep-9syGjvhHoSjbv2kKIwtc5ppq8v/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA803 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPAE804 (EJECUTIVA)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1mqtpNYQCjbaaKyvqeEUX_Lhcxfs-8sA0/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA901 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1-Xf1aBT1JGl8r5K3nEgJexVo9_Gtl0SF/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA1001 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1n7BuJFxZBXh-m78LlgZ0UEBKTVjbt9b6/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA1101 (Estadía)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>                            
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1bh16W6_b0Pwbflo_TP18fGwz2-MU6u67/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA1102 (Estadía)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="https://drive.google.com/file/d/1JB_ec777-mrG0u7taS6Vg_tPTDsxGVNT/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA1103 (Estadía)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>