                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">Listas de Grupo 2024-3</h1>
                            <p class="py-3 text-center">
                                Actualización 30/08/2024 20:12 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-6 col-12">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>IRD</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1Jbb5nH0QZ7iOngVvIOiPlkrOH39GON-6/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD101
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/13YMqHMBLeO3Oq0B2UCjSF2_JZdsxVkn6/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD102
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1T_LcKCg6dO5Vh9sUfF5gvGfV8A5IT-j7/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD401
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1wwmYeqtaqAscLREZLQmdQ4U1Z22bEdXw/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                IRD402
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 col-12">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>IRICE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRICE 701 (EJECUTIVA)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRICE 702 (EJECUTIVA)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRICE 1001 (EJECUTIVA)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="#" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            IRICE 1002 (EJECUTIVA)
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>