                        <div class="row contenido">

                            <div class="col-12 rounded shadow-sm rounded pb-5">
                                
                                <h1 class="py-3 text-center">Listas de Grupo 2025-2</h1>
                                <h2 class="py-3 text-center">Ciencia de Datos</h2>
                                <p class="py-3 text-center">
                                    Actualización 27/04/2025 08:03 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>CD</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    CD301
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                <br>
                                <br>
                                <h2 class="py-3 text-center">Infraestructura de Redes Digitales e Ingeniería en Redes Inteligentes y Ciberseguridad</h2>
                                <p class="py-3 text-center">
                                    Actualización 27/04/2025 08:01 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>IRD</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRD301
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRD302
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>IRICE</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE801 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE901 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    IRICE902 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <br>
                                <br>
                                <h2 class="py-3 text-center">Diseño y Animación Digital</h2>
                                <p class="py-3 text-center">
                                    Actualización 19/12/2024 10:12 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>DAD</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD201
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD301
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD302
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD303
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD304
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD305 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD306 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD307 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD308 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD309 (Vespertino)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <br>
                                <br>
                                <h2 class="py-3 text-center">Diseño Digital área Animación y Licenciatura en Diseño Digital y Producción Audiovisual</h2>
                                <p class="py-3 text-center">
                                    Actualización 27/04/2025 08:01 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>DDA</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA401
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA501
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>LDDPA</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA701
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA801
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA802
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA901
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA902
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA903
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPAE904 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA1001
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <br>
                                <br>
                                <h2 class="py-3 text-center">Descarga todos los Horarios de Grupo</h2>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Diseño, Redes y Ciencia de Datos</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="#" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    Horarios de Grupo 2025-2
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>