                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">Listas de Grupo 2024-2</h1>
                            <p class="py-3 text-center">
                                Actualización 21/05/2024 21:22 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12">
                                    
                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN ADMINISTRACIÓN ÁREA CAPITAL HUMANO</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                              <td>ACH-101x</td>
                                              <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-101</i></a></td>
                                              
                                            </tr>
                                            <tr>
                                              <td>ACH-201</td>
                                              <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-201</i></a></td>
                                              
                                            </tr>
                                            <tr>
                                                <td>ACH-301</td>
                                                <td><a href="https://drive.google.com/file/d/1s5yoPtvfz1n_204OGtL3ao31Gh4QQlKj/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-302</td>
                                                <td><a href="https://drive.google.com/file/d/1K2fffuLOaRDxRw60AfxNprKm75-dwYa2/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-302</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-303</td>
                                                <td><a href="https://drive.google.com/file/d/1ofTNq64Klsk7_BOJjsR0oGN7WvxsBsKQ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-303</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-305</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-305</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-306</td>
                                                <td><a href="https://drive.google.com/file/d/1STom6cuWfe0ZeY_uPmQwnrFzHmaApATv/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-306</i></a></td>
                                            </tr>
                                            <tr>    
                                                <td>ACH-308</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-308</i></a></td>
                                            </tr> -->
                                            <tr>
                                                <td>ACH-310</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-310</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-311</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-311</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-401</td>
                                                <td><a href="https://drive.google.com/file/d/1BmxmVy19QwIBxpdjyT-idwP7mt8p24M-/view?usp=sharingk" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-501</td>
                                                <td><a href="https://drive.google.com/file/d/1mBt6NOTaamn0PCiKUPIpuuMYJU4ADjW7/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-501</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                            <thead>
                                                <tr>
                                                <th style="width: 90%;">LICENCIATURA EN GESTIÓN DE CAPITAL HUMANO</th>
                                                <th style="width: 10%;">HORARIOS</th>
                                                
                                                </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LGCH-801</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-801</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-801 (EJECUTIVA)</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-801</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-901</td>
                                                <td><a href="https://drive.google.com/file/d/1U7uUtscstq1PhMM8u_Q8IbNuiunEZRKB/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-901</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-902</td>
                                                <td><a href="https://drive.google.com/file/d/1U7uUtscstq1PhMM8u_Q8IbNuiunEZRKB/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-902</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-903</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-903</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-903 (EJECUTIVA)</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-903</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCGH-904</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCGH-904</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCGHE-904 (EJECUTIVA)</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCGHE-904</i><Ea></td>
                                            </tr>
                                            <tr>
                                                <td>LCGH-905</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCGH-905</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCGHE-905 (EJECUTIVA)</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCGHE-905</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCGH-1001</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCGH-1001</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCGHE-1001 (EJECUTIVA)</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCGHE-1001</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN CONTADURÍA</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                        </thead>
                                          <tbody>
                                            <tr>
                                                <td>CT-101</td>
                                                <td><a href="https://drive.google.com/open?id=1_SY9AjMoi0qRond_iq9NtrBohynBjZ-1&usp=drive_copy" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-101</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-201</td>
                                                <td><a href="https://drive.google.com/file/d/165Whtd3RlOnw7zYocfxf4lx99cvDP9di/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-201</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-301</td>
                                                <td><a href="https://drive.google.com/file/d/1PYPOfdBBmnRSim9FgZsJ13LqF5zFcy-s/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-302</td>
                                                <td><a href="https://drive.google.com/file/d/1P22T9csAwNjW8Wftpemev70lUIcf1uTH/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-302</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-303</td>
                                                <td><a href="https://drive.google.com/file/d/1zzkAU1xjfuxzia4B_fMC2UyVJJlI1Nuw/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-303</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-305</td>
                                                <td><a href="https://drive.google.com/file/d/1Fa2dP_BAPZ04OhLyJ_znXCubnSyHdtB3/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-305</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-306</td>
                                                <td><a href="https://drive.google.com/file/d/10J1eYd1ALh4K38lFi_azw_kJFzpBvTLR/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-306</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-401</td>
                                                <td><a href="https://drive.google.com/file/d/1keQxG2g_8b2RJYgaomAq2PHgQ_onVsa-/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-501</td>
                                                <td><a href="https://drive.google.com/file/d/1mBt6NOTaamn0PCiKUPIpuuMYJU4ADjW7/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-501</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN CONTADURÍA</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LCTE-701 (EJECUTIVA)</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-701</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-801</td>
                                                <td><a href="https://drive.google.com/file/d/1FmXgByuCt1tLh0XXSJvXjSGOEK7G0WCi/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-801</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-802 (EJECUTIVA)</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-802</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-901</td>
                                                <td><a href="https://drive.google.com/file/d/1x_IMdhBMpCpInwTG4dkYPf9Gy-IXCl_q/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-901</i></a></td>
                                            </tr>
                                            <tr>
                                            <td>LCTE-902 (EJECUTIVA)</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-902</i></a>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-903 (EJECUTIVA)</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-903</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-1001 (EJECUTIVA)</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-1001</i></a></td>
                                            </tr>
                                            
                                          </tbody>
                                    </table>

                                </div>                                
                            </div>
                        </div>
                    </div>