<div class="row contenido">

    <div class="col-12 rounded shadow-sm rounded pb-5">
        
        <h1 class="py-3 text-center">Listas de Grupo 2025-1</h1>
        <h2 class="py-3 text-center">Ciencia de Datos</h2>
        <p class="py-3 text-center">
            Actualización 19/12/2024 10:12 p.m.
        </p>
        <div class="row">
            <div class="col-md-6 col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>CD</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            CD201
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <br>
        <br>
        <h2 class="py-3 text-center">Infraestructura de Redes Digitales e Ingeniería en Redes Inteligentes y Ciberseguridad</h2>
        <p class="py-3 text-center">
            Actualización 19/12/2024 10:12 p.m.
        </p>
        <div class="row">
            <div class="col-md-6 col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>IRD</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRD201
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRD202
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRD501
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRD502
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="col-md-6 col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>IRICE</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRICE701 (EJECUTIVA)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRICE801 (EJECUTIVA)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            IRICE802 (EJECUTIVA)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br>
        <br>
        <h2 class="py-3 text-center">Diseño y Animación Digital</h2>
        <p class="py-3 text-center">
            Actualización 19/12/2024 10:12 p.m.
        </p>
        <div class="row">
            <div class="col-md-6 col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>DAD</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD101
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD201
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD202
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD203
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD204
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD205 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD206 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD207 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD208 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DAD209 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br>
        <br>
        <h2 class="py-3 text-center">Diseño Digital área Animación y Licenciatura en Diseño Digital y Producción Audiovisual</h2>
        <p class="py-3 text-center">
            Actualización 19/12/2024 10:12 p.m.
        </p>
        <div class="row">
            <div class="col-md-6 col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>DDA</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA301
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA401
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA501
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA502
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA503
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA504 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            DDA505 (Vespertino)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="col-md-6 col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>LDDPA</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA701
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA702
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA801
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA802
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA803
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPAE804 (EJECUTIVA)
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA901
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="liLinks my-1">
                                    <a href="#" target="_blank" rel="noopener noreferrer">
                                        <div class="centrado-v">
                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                            LDDPA1001
                                        </div>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>