                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center text-danger">Mapas Curriculares</h1>
                            <p class="py-3 text-center">
                                Actualización 24/02/2025 09:29 p.m.
                            </p>
                            <div class="row">
                                <div class="col-12">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Programa:</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1jHNXON0FtqQgEWWyzM6MoVZcM2KlU1mX/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Ciencia de Datos
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1U4hplwSzo1p6riLyeh56Vd86oOzF6fbO/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                Infraestructura de Redes Digitales
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1ixXZwVxI4a6oRY29HQVKMQeOa9LxepCs/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                Diseño y Animación Digital
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>