                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=inicio" class="py-3">
                            <i class="bx bxs-home mx-2"></i>
                            <span class="links_name">Inicio</span>
                        </a>
                    </li>                 
                </ul>
                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=horarios" class="py-3">
                            <i class="bx bx-calendar mx-2"></i>
                            <span class="links_name">Horarios</span>
                        </a>
                    </li>                 
                </ul>
                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=aulas" class="py-3">
                            <i class="bx bxs-school mx-2"></i>
                            <span class="links_name">Aulas</span>
                        </a>
                    </li>                 
                </ul>
                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=califica" class="py-3">
                            <i class="bx bx-book-bookmark mx-2"></i>
                            <span class="links_name">Calificaciones</span>
                        </a>
                    </li>                 
                </ul>
                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=listas" class="py-3">
                            <i class="bx bx-user-voice mx-2"></i>
                            <span class="links_name">Listas</span>
                        </a>
                    </li>                 
                </ul>
                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=especiales" class="py-3">
                            <i class="bx bx-list-ul mx-2"></i>
                            <span class="links_name">Especiales</span>
                        </a>
                    </li>                 
                </ul>